FROM python:3.12-slim AS base

# Install system dependencies
RUN apt-get update \
    && apt-get install -y curl \
    && rm -rf /var/lib/apt/lists/*

# Install uv
RUN curl -LsSf https://astral.sh/uv/0.6.3/install.sh | sh

# Explicitly set PATH for all subsequent commands
ENV PATH="/root/.local/bin:$PATH"

# Set the working directory
WORKDIR /src

# # Install the dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project

# Production stage
FROM python:3.12-slim AS final

# Set the working directory
WORKDIR /src

# Copy venv from builder stage
COPY --from=base /src/.venv /src/.venv

# Update paths
ENV PATH="/src/.venv/bin:$PATH"
ENV PYTHONPATH="/src"

# Copy the rest of the application
COPY users/ .

# Run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
