apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-deployment
  labels:
    app.kubernetes.io/name: notifications-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: notifications-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: notifications-service
    spec:
      containers:
        - name: notifications-service
          image: jduran9987/mock-simpleservice-notifications
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
