apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app.kubernetes.io/name: users-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: users-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: users-service
    spec:
      containers:
        - name: users-service
          image: jduran9987/mock-simpleservice-users:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: NOTIFICATION_SERVICE_BASE_URL
              value: "http://notifications-service"
