apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels: 
    app.kubernetes.io/name: users-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: users-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
